# Generated by Django 5.1.1 on 2024-10-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('cnpj', models.CharField(max_length=18, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=45)),
                ('razao_social', models.CharField(max_length=45)),
                ('sede', models.CharField(max_length=45)),
                ('estado', models.CharField(max_length=45)),
                ('ranking', models.CharField(max_length=45)),
            ],
        ),
    ]
