# Generated by Django 5.1.1 on 2024-10-19 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area_cobertura',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('tecnologias', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='empresa_area_cobertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_cobertura_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_cobertura_id', to='backend.area_cobertura')),
                ('empresa_cnpj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_cnpj', to='backend.empresa')),
            ],
        ),
    ]
