# Generated by Django 5.1.1 on 2024-10-19 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_area_cobertura_empresa_area_cobertura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa_area_cobertura',
            name='empresa_cnpj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_empresa_cnpj', to='backend.empresa'),
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('banda', models.CharField(max_length=45)),
                ('empresa_cnpj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plano_empresa_cnpj', to='backend.empresa')),
            ],
        ),
    ]
