# Generated by Django 5.1.1 on 2024-10-19 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_empresa_area_cobertura_empresa_cnpj_plano'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Infraestrutura',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('asn', models.CharField(max_length=45)),
                ('ptt', models.CharField(max_length=45)),
                ('bgp', models.CharField(max_length=45)),
                ('operadora_backbone', models.CharField(max_length=45)),
                ('capacidade_backbone', models.CharField(max_length=45)),
                ('empresa_cnpj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infra_empresa_cnpj', to='backend.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('tipo_plano', models.CharField(max_length=45)),
                ('sla', models.CharField(max_length=45)),
                ('preco', models.IntegerField()),
                ('empresa_cnpj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servico_empresa_cnpj', to='backend.empresa')),
                ('plano_empresa_cnpj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servico_plano_empresa_cnpj', to='backend.plano')),
                ('plano_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servico_plano_id', to='backend.plano')),
            ],
        ),
    ]
