# Generated by Django 5.1.1 on 2024-10-19 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_setor_infraestrutura_servico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('cpf', models.CharField(max_length=45, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=45)),
                ('cargo', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('telefone', models.CharField(max_length=45)),
                ('setor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoa_setor_id', to='backend.setor')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.CharField(max_length=45)),
                ('cidade', models.CharField(max_length=45)),
                ('bairro', models.CharField(max_length=45)),
                ('empresa_cnpj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endereco_empresa_cnpj', to='backend.empresa')),
                ('pessoa_cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endereco_pessoa_cpf', to='backend.pessoa')),
            ],
        ),
    ]
